export const FETCH_COMPANY = "FETCH_COMPANY"
export const FETCH_COMPANY_FAIL = "FETCH_COMPANY_FAIL"
export const FETCH_COMPANY_SUCCESS = "FETCH_COMPANY_SUCCESS"

export const FETCH_COMPANY_BY_ID = "FETCH_COMPANY_BY_ID"
export const FETCH_COMPANY_FAIL_BY_ID = "FETCH_COMPANY_FAIL_BY_ID"
export const FETCH_COMPANY_SUCCESS_BY_ID = "FETCH_COMPANY_SUCCESS_BY_ID"

export const ADD_NEW_COMPANY = "ADD_NEW_COMPANY"
export const ADD_COMPANY_SUCCESS = "ADD_COMPANY_SUCCESS"
export const ADD_COMPANY_FAIL = "ADD_COMPANY_FAIL"
// update jobWbs
export const UPDATE_COMPANY = "UPDATE_COMPANY"
export const UPDATE_COMPANY_SUCCESS = "UPDATE_COMPANY_SUCCESS"
export const UPDATE_COMPANY_FAIL = "UPDATE_COMPANY_FAIL"
// delete jobWbs
export const DELETE_COMPANY = "DELETE_COMPANY"
export const DELETE_COMPANY_SUCCESS = "DELETE_COMPANY_SUCCESS"
export const DELETE_COMPANY_FAIL = "DELETE_COMPANY_FAIL"
