export const FETCH_JOB_WBS = "FETCH_JOB_WBS"
export const FETCH_JOB_WBS_FAIL = "FETCH_JOB_WBS_FAIL"
export const FETCH_JOB_WBS_SUCCESS = "FETCH_JOB_WBS_SUCCESS"

export const FETCH_JOB_WBS_BY_ID = "FETCH_JOB_WBS_BY_ID"
export const FETCH_JOB_WBS_FAIL_BY_ID = "FETCH_JOB_WBS_FAIL_BY_ID"
export const FETCH_JOB_WBS_SUCCESS_BY_ID = "FETCH_JOB_WBS_SUCCESS_BY_ID"

// Add jobWbs
export const ADD_NEW_JOB_WBS = "ADD_NEW_JOB"
export const ADD_JOB_WBS_SUCCESS = "ADD_JOB_SUCCESS"
export const ADD_JOB_WBS_FAIL = "ADD_JOB_FAIL"
// update jobWbs
export const UPDATE_JOB_WBS = "UPDATE_JOB_WBS"
export const UPDATE_JOB_WBS_SUCCESS = "UPDATE_JOB_WBS_SUCCESS"
export const UPDATE_JOB_WBS_FAIL = "UPDATE_JOB_WBS_FAIL"
// delete jobWbs
export const DELETE_JOB_WBS = "DELETE_JOB_WBS"
export const DELETE_JOB_WBS_SUCCESS = "DELETE_JOB_WBS_SUCCESS"
export const DELETE_JOB_WBS_FAIL = "DELETE_JOB_WBS_FAIL"
