import { jobApply } from "common/data"

export const FETCH_JOBLIST_USER = "FETCH_JOBLIST_USER"
export const FETCH_JOBLIST_USER_FAIL = "FETCH_JOBLIST_USER_FAIL"
export const FETCH_JOBLIST_USER_SUCCESS = "FETCH_JOBLIST_USER_SUCCESS"

export const FETCH_JOBLIST_USER_FOR_CALENDAR = "FETCH_JOBLIST_USER_FOR_CALENDAR"
export const FETCH_JOBLIST_USER_FAIL_FOR_CALENDAR =
  "FETCH_JOBLIST_USER_FAIL_FOR_CALENDAR"
export const FETCH_JOBLIST_USER_SUCCESS_FOR_CALENDAR =
  "FETCH_JOBLIST_USER_SUCCESS_FOR_CALENDAR"

export const FETCH_ALL_TECHNICIANS = "FETCH_ALL_TECHNICIANS"
export const FETCH_ALL_TECHNICIANS_SUCCESS = "FETCH_ALL_TECHNICIANS_SUCCESS"
export const FETCH_ALL_TECHNICIANS_FAIL = "FETCH_ALL_TECHNICIANS_FAIL"

export const FETCH_JOBLIST_USER_BY_PARAMS = "FETCH_JOBLIST_USER_BY_PARAMS"

export const FETCH_TECHNICIAN = "FETCH_TECHNICIAN"
export const FETCH_TECHNICIAN_FAIL = "FETCH_TECHNICIAN_FAIL"
export const FETCH_TECHNICIAN_SUCCESS = "FETCH_TECHNICIAN_SUCCESS"

// Add JOB_USER
export const ADD_NEW_TECHNICIAN = "ADD_NEW_TECHNICIAN"
export const ADD_JOB_TECHNICIAN_SUCCESS = "ADD_JOB_TECHNICIAN_SUCCESS"
export const ADD_JOB_TECHNICIAN_FAIL = "ADD_JOB_TECHNICIAN_FAIL"

export const UPDATE_JOB_TECHNICIAN = "UPDATE_JOB_TECHNICIAN"
export const UPDATE_JOB_TECHNICIAN_SUCCESS = "UPDATE_JOB_TECHNICIAN_SUCCESS"
export const UPDATE_JOB_TECHNICIAN_FAIL = "UPDATE_JOB_TECHNICIAN_FAIL"

export const DELETE_JOB_TECHNICIAN = "DELETE_JOB_TECHNICIAN"
export const DELETE_JOB_TECHNICIAN_SUCCESS = "DELETE_JOB_TECHNICIAN_SUCCESS"
export const DELETE_JOB_TECHNICIAN_FAIL = "DELETE_JOB_TECHNICIAN_FAIL"
