import { jobApply } from "common/data"

export const FETCH_JOBLIST_USER = "FETCH_JOBLIST_USER"
export const FETCH_JOBLIST_USER_FAIL = "FETCH_JOBLIST_USER_FAIL"
export const FETCH_JOBLIST_USER_SUCCESS = "FETCH_JOBLIST_USER_SUCCESS"

export const FETCH_ALL_TECHNICIANS = "FETCH_ALL_TECHNICIANS"
export const FETCH_ALL_TECHNICIANS_SUCCESS = "FETCH_ALL_TECHNICIANS_SUCCESS"
export const FETCH_ALL_TECHNICIANS_FAIL = "FETCH_ALL_TECHNICIANS_FAIL"

export const FETCH_JOBLIST_USER_BY_PARAMS = "FETCH_JOBLIST_USER_BY_PARAMS"

export const FETCH_JOB_USER = "FETCH_JOB_USER"
export const FETCH_JOB_USER_FAIL = "FETCH_JOB_USER_FAIL"
export const FETCH_JOB_USER_SUCCESS = "FETCH_JOB_USER_SUCCESS"

// Add JOB_USER
export const ADD_NEW_TECHNICIAN = "ADD_NEW_TECHNICIAN"
export const ADD_JOB_TECHNICIAN_SUCCESS = "ADD_JOB_TECHNICIAN_SUCCESS"
export const ADD_JOB_TECHNICIAN_FAIL = "ADD_JOB_TECHNICIAN_FAIL"

export const UPDATE_JOB_USER = "UPDATE_JOB_USER"
export const UPDATE_JOB_USER_SUCCESS = "UPDATE_JOB_USER_SUCCESS"
export const UPDATE_JOB_USER_FAIL = "UPDATE_JOB_USER_FAIL"
export const DELETE_JOB_USER = "DELETE_JOB_USER"
export const DELETE_JOB_USER_SUCCESS = "DELETE_JOB_USER_SUCCESS"
export const DELETE_JOB_USER_FAIL = "DELETE_JOB_USER_FAIL"
// export const GET_APPLY_JOB = "GET_APPLY_JOB"
// export const GET_APPLY_JOB_SUCCESS = "GET_APPLY_JOB_SUCCESS"
// export const GET_APPLY_JOB_FAIL = "GET_APPLY_JOB_FAIL"
// export const DELETE_APPLY_JOB = "DELETE_APPLY_JOB"
// export const DELETE_APPLY_JOB_SUCCESS = "DELETE_APPLY_JOB_SUCCESS"
// export const DELETE_APPLY_JOB_FAIL = "DELETE_APPLY_JOB_FAIL"
