import { jobApply } from "common/data"

export const FETCH_SITES = "FETCH_SITES"
export const FETCH_SITES_FAIL = "FETCH_SITES_FAIL"
export const FETCH_SITES_SUCCESS = "FETCH_SITES_SUCCESS"

export const FETCH_SITES_BY_PARAMS = "FETCH_SITES_BY_PARAMS"

export const FETCH_SITE = "FETCH_SITE"
export const FETCH_SITE_FAIL = "FETCH_SITE_FAIL"
export const FETCH_SITE_SUCCESS = "FETCH_SITE_SUCCESS"

// Add Site
export const ADD_NEW_SITE = "ADD_NEW_SITE"
export const ADD_SITE_SUCCESS = "ADD_SITE_SUCCESS"
export const ADD_SITE_FAIL = "ADD_SITE_FAIL"

export const UPDATE_SITE = "UPDATE_SITE"
export const UPDATE_SITE_SUCCESS = "UPDATE_SITE_SUCCESS"
export const UPDATE_SITE_FAIL = "UPDATE_SITE_FAIL"
export const DELETE_SITE = "DELETE_SITE"
export const DELETE_SITE_SUCCESS = "DELETE_SITE_SUCCESS"
export const DELETE_SITE_FAIL = "DELETE_SITE_FAIL"
